# Generated by Django 3.2 on 2023-04-29 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_user_unique_username_email'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_username_email',
        ),
    ]
