# Generated by Django 3.2.16 on 2023-04-30 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_remove_user_unique_username_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('id', 'name'), 'verbose_name': 'genre', 'verbose_name_plural': 'genres'},
        ),
    ]
