# Generated by Django 3.2 on 2023-04-30 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_user_email'),
        ('reviews', '0008_user_confirmation_code'),
    ]

    operations = [
    ]
