# Generated by Django 3.2 on 2023-05-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_merge_20230430_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50, unique=True, verbose_name='e-mail адрес'),
        ),
    ]
