# Generated by Django 3.2.16 on 2023-05-01 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20230430_1549'),
        ('reviews', '0010_alter_user_email'),
    ]

    operations = [
    ]
