# Generated by Django 3.2 on 2023-05-02 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_merge_0008_auto_20230430_1549_0010_alter_user_email'),
        ('reviews', '0012_auto_20230502_0858'),
    ]

    operations = [
    ]
