# Generated by Django 3.2.16 on 2023-05-05 18:15

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0016_auto_20230504_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveIntegerField(help_text='Год выхода произведения', validators=[api.validators.validate_year]),
        ),
    ]
